### ISSUE TITLE
Entry point script not found

### ISSUE THREAD

**Issue by LeZuse** [Klowner/docker-localnpm#1]
When I run the quick start command

```
docker run -d -v "$PWD":/data -p 5080:5080 klowner/local-npm
```

I get an error:

```
docker: Error response from daemon: Container command '/app/entrypoint.sh' not found or does not exist..
```

**Comment by Klowner** [comment]
Sorry about that! All should be working now, please `git pull klowner/local-npm` and give it another try.

Not sure how I managed to goof that up so well.

**Comment by Klowner** [comment]
Looks fixed from here, please re-open if you're still having issues.
